version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hackwarts
      - MONGO_INITDB_ROOT_PASSWORD=hackwarts2024
  
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hackwarts
      ME_CONFIG_MONGODB_ADMINPASSWORD: hackwarts2024
      ME_CONFIG_MONGODB_URL: mongodb://hackwarts:hackwarts2024@mongodb:27017/hackwarts?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:

